[package]
name = "rayo"
version = "0.1.0"
edition = "2018"

[dependencies]
rand = "0.8.4" # random numbers
image = "0.23.14" # ez image writing
rayon = "1.5.1" # parallelization
indicatif = "0.16.2" # progres bar
clap = "2.33.3"